version: '3'
 
services:
 
   node:
     build:
        context: .
        dockerfile: Dockerfile
     command: yarn serve
     ports:
       - "8080:8080"
     working_dir: /app
     volumes:
       - ".:/app"